# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.3.0"

[source]
paths = ["app/", "database/factories/", "database/seeders/", "tests/"]
includes = []
excludes = ["vendor"]

[formatter]
print-width = 100
tab-width = 4
use-tabs = false
method-chain-breaking-style = "next_line"
inline-empty-function-braces = true


[linter]
integrations = ["laravel"]


[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }

[analyzer]
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = false
check-throws = true
allow-possibly-undefined-array-keys = true
perform-heuristic-checks = true
